import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

const ASCII_ALIEN = `
MMMMMMMMMMMMMMWNNNXXXXKKKKKKKXXXNNWWWMMMMMMMMMMMMM
MMMMMMMMMMWWNXXKKKKKKKKKKKKKKKKKKKKXXNWWMMMMMMMMMM
MMMMMMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNWMMMMMMMM
MMMMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWMMMMMM
MMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWMMMM
MMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWMMM
MMWNKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNWMM
MWNKKKOxdddkOKKKKKKKKKKKKKKKKKKKKKKKKOkdddxOKKKNMM
MWXKKk;.....,:ok0KKKKKKKKKKKKKKKK0ko:,.....;kKKXWM
MNKKKo.........':d0KKKKKKKKKKKK0d:'.........oKKKNW
WXKKKx,...........;d0KKKKKKKK0d;...........,xKKKXW
WXKKK0d,...........'cOKKKKKKOc'...........,dKKKKXW
WXKKKKKx;............:kKKKKk:............;xKKKKKXW
MNXKKKKKOl,...........cOKKOc...........,lOKKKKKKNM
MWXKKKKKKKkl,.........,xKKx,.........,lkKKKKKKKXWM
MMWXKKKKKKKKOxc;'.....cOKKOc.....';cdOKKKKKKKKXWMM
MMMWXKKKKKKKKKK0kxdodx0KKKK0xdodxk0KKKKKKKKKKXWMMM
MMMMWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWMMMM
MMMMMMWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXWMMMMMM
MMMMMMMWNXKKKKKKKK0l:ldxkkxdl:l0XKKKKKKKXNWMMMMMMM
MMMMMMMMMWNXKKKKKK0d:'''''''';d0KKKKKKXNWMMMMMMMMM
MMMMMMMMMMMWNXXKKKKK0OkxdxxxO0KKKKKXXNWMMMMMMMMMMM
MMMMMMMMMMMMMMWNXKKKKKKKKKKKKKKKKXNWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWWNXXKKKKKKKKXXNWWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWWNXXKXXXNWWMMMMMMMMMMMMMMMMMMM
`;

console.log(ASCII_ALIEN);
console.log('Klaatu barada nikto');

const rootElement = document.getElementById('root');
if (rootElement) {
  createRoot(rootElement).render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
} else {
  console.error('Root element not found');
}
